s1 = input('Добрый день! Как Вас зовут?')
print('Добро пожаловать,', s1)
s2 = input("Сколько Вам полных лет?")
print('Ваш возраст - ', s2)
print('Длина первой строки - ', len(s1))
print('Длина второй строки - ', len(s2))
print(s1[0])
print(s2[len(s2) - 1])
print(s1 == s2)
print(s1.count(s2))
print(s2.count(s1))